"""Add ativo field to Usuario model

Revision ID: 32e43cab3e28
Revises: 8611c685f75b
Create Date: 2025-10-26 04:26:40.915723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e43cab3e28'
down_revision = '8611c685f75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # As colunas de estoques já foram adicionadas na migration 9f7c2d4b1e3f
    # Esta migration apenas adiciona o campo 'ativo' em usuarios
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
