"""add solicitacoes restaurante table and notification type

Revision ID: 415b31d526d2
Revises: f1a2b3c4d5e6
Create Date: 2026-01-04 00:44:53.233539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415b31d526d2'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_restaurante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_restaurante', sa.String(length=200), nullable=False),
    sa.Column('endereco_restaurante', sa.String(length=400), nullable=False),
    sa.Column('telefone_restaurante', sa.String(length=20), nullable=False),
    sa.Column('email_restaurante', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=100), nullable=False),
    sa.Column('email_responsavel', sa.String(length=120), nullable=False),
    sa.Column('telefone_responsavel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statussolicitacaorestaurante'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('processado_em', sa.DateTime(), nullable=True),
    sa.Column('processado_por_id', sa.Integer(), nullable=True),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True),
    sa.Column('restaurante_criado_id', sa.Integer(), nullable=True),
    sa.Column('usuario_admin_criado_id', sa.Integer(), nullable=True),
    sa.Column('senha_gerada', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['processado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurante_criado_id'], ['restaurantes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_admin_criado_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convite_tokens', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'COLLABORATOR', name='userroles'),
               existing_nullable=False,
               postgresql_using='role::userroles')
        batch_op.drop_constraint(batch_op.f('convite_tokens_token_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_convite_tokens_token'))
        batch_op.create_index(batch_op.f('ix_convite_tokens_token'), ['token'], unique=True)

    with op.batch_alter_table('listas_rapidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listas_rapidas_status'))
        batch_op.drop_index(batch_op.f('ix_listas_rapidas_usuario_id'))

    with op.batch_alter_table('listas_rapidas_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listas_rapidas_itens_lista_id'))
        batch_op.drop_index(batch_op.f('ix_listas_rapidas_itens_prioridade'))

    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('restaurantes_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_restaurantes_slug'))
        batch_op.create_index(batch_op.f('ix_restaurantes_slug'), ['slug'], unique=True)

    with op.batch_alter_table('sugestoes_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sugestoes_itens_status'))
        batch_op.drop_index(batch_op.f('ix_sugestoes_itens_usuario_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('sugestoes_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sugestoes_itens_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sugestoes_itens_status'), ['status'], unique=False)

    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurantes_slug'))
        batch_op.create_index(batch_op.f('ix_restaurantes_slug'), ['slug'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('restaurantes_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('listas_rapidas_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listas_rapidas_itens_prioridade'), ['prioridade'], unique=False)
        batch_op.create_index(batch_op.f('ix_listas_rapidas_itens_lista_id'), ['lista_rapida_id'], unique=False)

    with op.batch_alter_table('listas_rapidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listas_rapidas_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listas_rapidas_status'), ['status'], unique=False)

    with op.batch_alter_table('convite_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convite_tokens_token'))
        batch_op.create_index(batch_op.f('ix_convite_tokens_token'), ['token'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('convite_tokens_token_key'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'COLLABORATOR', name='userroles'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    op.drop_table('solicitacoes_restaurante')
    # ### end Alembic commands ###
