"""Add descricao field to Lista model

Revision ID: 4688e2f3a1aa
Revises: 7d59f933ff26
Create Date: 2025-10-24 09:54:48.735449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4688e2f3a1aa'
down_revision = '7d59f933ff26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
