"""Add Notificacao model for persistent notifications

Revision ID: 6bdfcf9edae2
Revises: a31745469f02
Create Date: 2026-01-02 04:58:39.595881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdfcf9edae2'
down_revision = 'a31745469f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('submissao_lista', 'submissao_lista_rapida', 'sugestao_item', 'lista_aprovada', 'lista_rejeitada', 'item_sugerido_aprovado', 'item_sugerido_rejeitado', 'pedido_aprovado', 'pedido_rejeitado', name='tiponotificacao'), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=True),
    sa.Column('lista_rapida_id', sa.Integer(), nullable=True),
    sa.Column('submissao_id', sa.Integer(), nullable=True),
    sa.Column('sugestao_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('lido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lista_rapida_id'], ['listas_rapidas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submissao_id'], ['submissoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sugestao_id'], ['sugestoes_itens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
