"""add supplier models and fields

Revision ID: 6d49e2aeb1bf
Revises: 70b8295d7413
Create Date: 2026-01-23 00:38:55.161856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d49e2aeb1bf'
down_revision = '70b8295d7413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userroles ADD VALUE IF NOT EXISTS 'SUPPLIER'")

    op.create_table('convite_fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('usado_por_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convite_fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convite_fornecedores_criado_por_id'), ['criado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_convite_fornecedores_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_convite_fornecedores_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_convite_fornecedores_usado_por_id'), ['usado_por_id'], unique=False)

    op.create_table('item_preco_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('preco_anterior', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('preco_novo', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('alterado_em', sa.DateTime(), nullable=False),
    sa.Column('alterado_por_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['alterado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_preco_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_preco_historico_alterado_por_id'), ['alterado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_preco_historico_item_id'), ['item_id'], unique=False)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('site', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('aprovado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        batch_op.create_index(batch_op.f('ix_fornecedores_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_fornecedor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preco_atual', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.alter_column('aprovado', server_default=None)
        batch_op.alter_column('criado_em', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('preco_atual')
        batch_op.drop_column('marca')
        batch_op.drop_column('descricao')
        batch_op.drop_column('codigo_fornecedor')

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fornecedores_usuario_id'))
        batch_op.drop_column('criado_em')
        batch_op.drop_column('aprovado')
        batch_op.drop_column('site')
        batch_op.drop_column('cep')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('endereco')
        batch_op.drop_column('telefone')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('item_preco_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_preco_historico_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_preco_historico_alterado_por_id'))

    op.drop_table('item_preco_historico')
    with op.batch_alter_table('convite_fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convite_fornecedores_usado_por_id'))
        batch_op.drop_index(batch_op.f('ix_convite_fornecedores_token'))
        batch_op.drop_index(batch_op.f('ix_convite_fornecedores_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_convite_fornecedores_criado_por_id'))

    op.drop_table('convite_fornecedores')
    # ### end Alembic commands ###
