"""add restaurante_id to notificacoes table

Revision ID: 70b8295d7413
Revises: 0f1a2b3c4d5e
Create Date: 2026-01-21 00:17:16.869129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b8295d7413'
down_revision = '0f1a2b3c4d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas', schema=None) as batch_op:
        batch_op.alter_column('restaurante_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurante_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notificacoes_restaurante_id'), ['restaurante_id'], unique=False)
        batch_op.create_foreign_key(None, 'restaurantes', ['restaurante_id'], ['id'], ondelete='SET NULL')

    # Popular dados existentes: inferir restaurante_id do usuário
    op.execute("""
        UPDATE notificacoes
        SET restaurante_id = (
            SELECT restaurante_id
            FROM usuarios
            WHERE usuarios.id = notificacoes.usuario_id
        )
        WHERE usuario_id IS NOT NULL
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notificacoes_restaurante_id'))
        batch_op.drop_column('restaurante_id')

    with op.batch_alter_table('listas', schema=None) as batch_op:
        batch_op.alter_column('restaurante_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
