"""Adiciona status ao modelo Cotacao

Revision ID: 7d59f933ff26
Revises: c568f5f72228
Create Date: 2025-10-19 01:25:47.854789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d59f933ff26'
down_revision = 'c568f5f72228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar ENUM para CotacaoStatus (PostgreSQL precisa disso explicitamente)
    cotacaostatus = sa.Enum('PENDENTE', 'CONCLUIDA', name='cotacaostatus')
    cotacaostatus.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', cotacaostatus, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # Dropar ENUM
    cotacaostatus = sa.Enum('PENDENTE', 'CONCLUIDA', name='cotacaostatus')
    cotacaostatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
