"""add limite_usos and quantidade_usos to convite_restaurantes

Revision ID: 7dabacb9feec
Revises: a7b8c9d0e1f2
Create Date: 2026-01-20 17:26:23.281294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dabacb9feec'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convite_restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_usos', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('quantidade_usos', sa.Integer(), nullable=False, server_default='0'))

    # Atualiza convites existentes: se usado=True, quantidade_usos=1
    op.execute("UPDATE convite_restaurantes SET quantidade_usos = 1 WHERE usado = true")

    with op.batch_alter_table('fornecedor_item_codigos', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_fornecedor_item_codigos_fornecedor'))
        batch_op.drop_index(batch_op.f('ix_fornecedor_item_codigos_item'))
        batch_op.create_index(batch_op.f('ix_fornecedor_item_codigos_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedor_item_codigos_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor_item_codigos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedor_item_codigos_item_id'))
        batch_op.drop_index(batch_op.f('ix_fornecedor_item_codigos_fornecedor_id'))
        batch_op.create_index(batch_op.f('ix_fornecedor_item_codigos_item'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedor_item_codigos_fornecedor'), ['fornecedor_id'], unique=False)
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('convite_restaurantes', schema=None) as batch_op:
        batch_op.drop_column('quantidade_usos')
        batch_op.drop_column('limite_usos')

    # ### end Alembic commands ###
