"""add checklists de compras

Revision ID: 92ebf6077eb3
Revises: 79b5e3993890
Create Date: 2025-12-29 03:15:42.759988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ebf6077eb3'
down_revision = '79b5e3993890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submissao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'FINALIZADO', name='checkliststatus'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submissao_id'], ['submissoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('item_nome', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('fornecedor_nome', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('marcado', sa.Boolean(), nullable=False),
    sa.Column('marcado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_itens')
    op.drop_table('checklists')
    # ### end Alembic commands ###
