"""Add ListaMaeItem model for master list items

Revision ID: a1b2c3d4e5f6
Revises: c568f5f72228
Create Date: 2025-11-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'c568f5f72228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_mae_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_mae_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('quantidade_atual', sa.Float(), nullable=False),
    sa.Column('quantidade_minima', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lista_mae_id'], ['listas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista_mae_itens')
    # ### end Alembic commands ###
