"""Add descartado field to ListaRapidaItem

Revision ID: a31745469f02
Revises: d1e2f3a4b5c6
Create Date: 2026-01-02 03:08:42.954010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31745469f02'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas_rapidas_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descartado', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas_rapidas_itens', schema=None) as batch_op:
        batch_op.drop_column('descartado')

    # ### end Alembic commands ###
