"""Add soft delete fields to Lista model

Revision ID: soft_delete_listas
Revises: 32e43cab3e28
Create Date: 2025-11-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'soft_delete_listas'
down_revision = '32e43cab3e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('data_delecao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas', schema=None) as batch_op:
        batch_op.drop_column('data_delecao')
        batch_op.drop_column('deletado')

    # ### end Alembic commands ###
