"""Adicionar campo senha_texto_puro ao modelo Usuario

Revision ID: ae3d07c79900
Revises: b7c3e9d1f2a4
Create Date: 2026-01-07 02:42:46.268400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3d07c79900'
down_revision = 'b7c3e9d1f2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_texto_puro', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('senha_texto_puro')

    # ### end Alembic commands ###
