"""Criar tabela de convites de usuários

Revision ID: c1d2e3f4g5h6
Revises: 6bdfcf9edae2
Create Date: 2026-01-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g5h6'
down_revision = '6bdfcf9edae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'COLLABORATOR', name='userroles', native_enum=False), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False, server_default='0'),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('usado_por_id', sa.Integer(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_convite_tokens_token', 'convite_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_convite_tokens_token', table_name='convite_tokens')
    op.drop_table('convite_tokens')
    # ### end Alembic commands ###
