"""Adiciona status ao modelo Pedido

Revision ID: c568f5f72228
Revises: c877254787d7
Create Date: 2025-10-18 23:34:55.473973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c568f5f72228'
down_revision = 'c877254787d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar ENUM para PedidoStatus (PostgreSQL precisa disso explicitamente)
    pedidostatus = sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='pedidostatus')
    pedidostatus.create(op.get_bind(), checkfirst=True)
    
    op.create_table('listas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lista_colaborador',
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('lista_id', 'usuario_id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', pedidostatus, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('lista_colaborador')
    op.drop_table('listas')
    
    # Dropar ENUM
    pedidostatus = sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='pedidostatus')
    pedidostatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
