"""Add fornecedor_id to Item model

Revision ID: c877254787d7
Revises: 173f5518beb9
Create Date: 2025-10-18 02:27:01.438124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c877254787d7'
down_revision = '173f5518beb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fornecedor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_item_fornecedor', 'fornecedores', ['fornecedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_fornecedor', type_='foreignkey')
        batch_op.drop_column('fornecedor_id')

    # ### end Alembic commands ###
