"""add ativo field to convite_restaurantes

Revision ID: ef262cbdd9ad
Revises: 7dabacb9feec
Create Date: 2026-01-20 18:10:47.237179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef262cbdd9ad'
down_revision = '7dabacb9feec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convite_restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convite_restaurantes', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
