"""add temp items support to lista rapida

Revision ID: f2f0961bd9e4
Revises: 67549846fa66
Create Date: 2025-12-30 04:14:37.664730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f0961bd9e4'
down_revision = '67549846fa66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Adicionar suporte a itens temporários em listas rápidas
    with op.batch_alter_table('listas_rapidas_itens', schema=None) as batch_op:
        # Tornar item_global_id nullable (permitir itens temporários)
        batch_op.alter_column('item_global_id', nullable=True)
        # Adicionar campos para itens temporários
        batch_op.add_column(sa.Column('item_nome_temp', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('item_unidade_temp', sa.String(length=50), nullable=True))

    # Adicionar suporte a listas rápidas em sugestões
    with op.batch_alter_table('sugestoes_itens', schema=None) as batch_op:
        # Tornar lista_id nullable (permitir sugestões de listas rápidas)
        batch_op.alter_column('lista_id', nullable=True)
        # Adicionar FK para listas rápidas
        batch_op.add_column(sa.Column('lista_rapida_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sugestoes_lista_rapida', 'listas_rapidas', ['lista_rapida_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Reverter mudanças em sugestões
    with op.batch_alter_table('sugestoes_itens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sugestoes_lista_rapida', type_='foreignkey')
        batch_op.drop_column('lista_rapida_id')
        batch_op.alter_column('lista_id', nullable=False)

    # Reverter mudanças em itens de listas rápidas
    with op.batch_alter_table('listas_rapidas_itens', schema=None) as batch_op:
        batch_op.drop_column('item_unidade_temp')
        batch_op.drop_column('item_nome_temp')
        batch_op.alter_column('item_global_id', nullable=False)

    # ### end Alembic commands ###
