"""Initial database migration.

Revision ID: 173f5518beb9
Revises: 
Create Date: 2025-10-18 01:57:40.967432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173f5518beb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('meio_envio', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COLLABORATOR', name='userroles'), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('data_cotacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_minima', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotacao_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotacao_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['cotacao_id'], ['cotacoes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotacao_itens')
    op.drop_table('pedidos')
    op.drop_table('estoques')
    op.drop_table('cotacoes')
    op.drop_table('usuarios')
    op.drop_table('itens')
    op.drop_table('fornecedores')
    op.drop_table('areas')
    # ### end Alembic commands ###
