"""Add ativo field to Usuario model

Revision ID: 32e43cab3e28
Revises: 8611c685f75b
Create Date: 2025-10-26 04:26:40.915723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e43cab3e28'
down_revision = '8611c685f75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lista_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pedido', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('data_ultima_submissao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_ultima_submissao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_estoques_usuario_ultima_submissao', 'usuarios', ['usuario_ultima_submissao_id'], ['id'])
        batch_op.create_foreign_key('fk_estoques_lista', 'listas', ['lista_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estoques_usuario_ultima_submissao', type_='foreignkey')
        batch_op.drop_constraint('fk_estoques_lista', type_='foreignkey')
        batch_op.drop_column('usuario_ultima_submissao_id')
        batch_op.drop_column('data_ultima_submissao')
        batch_op.drop_column('pedido')
        batch_op.drop_column('lista_id')

    # ### end Alembic commands ###
