"""add username field to Usuario model

Revision ID: 8611c685f75b
Revises: 4688e2f3a1aa
Create Date: 2025-10-25 01:57:19.610275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8611c685f75b'
down_revision = '9f7c2d4b1e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_usuarios_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
