"""Add pedido calculation fields and audit trail to Estoque model

Revision ID: 9f7c2d4b1e3f
Revises: 4688e2f3a1aa
Create Date: 2025-10-25 14:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7c2d4b1e3f'
down_revision = '4688e2f3a1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lista_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pedido', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('data_ultima_submissao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_ultima_submissao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_estoque_lista_id', 'listas', ['lista_id'], ['id'])
        batch_op.create_foreign_key('fk_estoque_usuario_submissao_id', 'usuarios', ['usuario_ultima_submissao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estoque_usuario_submissao_id', type_='foreignkey')
        batch_op.drop_constraint('fk_estoque_lista_id', type_='foreignkey')
        batch_op.drop_column('usuario_ultima_submissao_id')
        batch_op.drop_column('data_ultima_submissao')
        batch_op.drop_column('pedido')
        batch_op.drop_column('lista_id')

    # ### end Alembic commands ###
