"""Add responsavel and observacao fields to Fornecedor

Revision ID: c73c13f3b371
Revises: de9b2e523935
Create Date: 2025-11-22 13:36:39.266197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73c13f3b371'
down_revision = 'de9b2e523935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add responsavel and observacao columns to fornecedores table
    from sqlalchemy.engine.reflection import Inspector

    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('fornecedores')]

    # Only add columns if they don't exist
    if 'responsavel' not in columns:
        with op.batch_alter_table('fornecedores', schema=None) as batch_op:
            batch_op.add_column(sa.Column('responsavel', sa.String(length=100), nullable=True))

    if 'observacao' not in columns:
        with op.batch_alter_table('fornecedores', schema=None) as batch_op:
            batch_op.add_column(sa.Column('observacao', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_column('observacao')
        batch_op.drop_column('responsavel')
    # ### end Alembic commands ###
