"""Add fornecedor_lista junction table

Revision ID: de9b2e523935
Revises: 74dbf5436c25
Create Date: 2025-11-22 03:54:56.776443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9b2e523935'
down_revision = '74dbf5436c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create fornecedor_lista junction table if it doesn't exist
    from alembic import context
    import sqlalchemy as sa
    from sqlalchemy.engine.reflection import Inspector

    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    # Only create if table doesn't exist
    if 'fornecedor_lista' not in tables:
        op.create_table('fornecedor_lista',
            sa.Column('fornecedor_id', sa.Integer(), nullable=False),
            sa.Column('lista_id', sa.Integer(), nullable=False),
            sa.Column('criado_em', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
            sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ),
            sa.PrimaryKeyConstraint('fornecedor_id', 'lista_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor_lista')
    # ### end Alembic commands ###
