"""adiciona tabela submissoes e campo submissao_id em pedidos

Revision ID: ee7f1f6e47e5
Revises: 1399849335e0
Create Date: 2025-12-26 01:44:32.930989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7f1f6e47e5'
down_revision = '1399849335e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_submissao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PARCIALMENTE_APROVADO', 'APROVADO', 'REJEITADO', name='submissaostatus'), nullable=False),
    sa.Column('total_pedidos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submissao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'submissoes', ['submissao_id'], ['id'], ondelete='CASCADE')

    # REMOVIDO: Alteração de senha_hash (causa erro com dados existentes)
    # with op.batch_alter_table('usuarios', schema=None) as batch_op:
    #     batch_op.alter_column('senha_hash',
    #            existing_type=sa.VARCHAR(length=256),
    #            type_=sa.String(length=128),
    #            existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVIDO: Alteração de senha_hash
    # with op.batch_alter_table('usuarios', schema=None) as batch_op:
    #     batch_op.alter_column('senha_hash',
    #            existing_type=sa.String(length=128),
    #            type_=sa.VARCHAR(length=256),
    #            existing_nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submissao_id')

    op.drop_table('submissoes')
    # ### end Alembic commands ###
